---
# tasks file for horizon configure

- name: Copy the configuration files for horizon.
  template:
    src: horizon_local_settings.j2
    dest: "{{ horizon_local_settings_location }}"
  notify:
    - restart horizon
    - restart memcached