---
# tasks file for ansible-role-openstack-horizon

# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/Install tasks.
- include: horizon_install_RedHat.yml
  when: ansible_os_family == 'RedHat'

# Configure tasks.
- include: horizon_configure.yml
