---
# handlers file for ansible-role-openstack-horizon

- name: restart horizon
  service:
    name: "{{ horizon_system_service_name }}"
    state: restarted

- name: restart memcached
  service:
    name: memcached
    state: restarted
